spring:
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      auto-index-creation: true
  mongodb:
    uri: mongodb://localhost:27017/kachi_notification?replicaSet=rs0
  kafka:
    bootstrap-servers: localhost:9092
