package me.rgunny.kachi.ai.adapter.inbound.web

object ApiPaths {
    const val INTERNAL_LLM_MODELS = "/internal/llm/models"
    const val INTERNAL_LLM_MODEL_RESET = "$INTERNAL_LLM_MODELS/{model}/reset"
    const val INTERNAL_LLM_MODEL_PROBE = "$INTERNAL_LLM_MODELS/{model}/probe"
    const val INTERNAL_AI_KEYWORD_EXPANSIONS = "/internal/ai/keyword-expansions"
    const val INTERNAL_AI_NEWS_SUMMARIES = "/internal/ai/news-summaries"
    const val INTERNAL_AI_KEYWORD_QUARANTINES = "/internal/ai/keyword-quarantines"
    const val INTERNAL_AI_KEYWORD_QUARANTINE_RELEASE = "$INTERNAL_AI_KEYWORD_QUARANTINES/{keyword}/release"
    const val INTERNAL_AI_SUMMARY_WATERMARKS = "/internal/ai/summary-watermarks"
    const val INTERNAL_AI_OUTBOXES = "/internal/ai/outboxes"
    const val INTERNAL_AI_OUTBOX_RECOVER = "$INTERNAL_AI_OUTBOXES/{outboxId}/recover"
    const val INTERNAL_AI_STORY_SUMMARIES = "/internal/ai/story-summaries"
    const val INTERNAL_AI_STORY_SUMMARY_RUN = "$INTERNAL_AI_STORY_SUMMARIES/run"
    const val INTERNAL_AI_STORY_QUARANTINES = "/internal/ai/story-quarantines"
    const val INTERNAL_AI_STORY_QUARANTINE_RELEASE = "$INTERNAL_AI_STORY_QUARANTINES/{storyId}/release"

    const val V1_INTERNAL_LLM_MODELS = "${ApiVersions.V1_PATH_PREFIX}$INTERNAL_LLM_MODELS"
    const val V1_INTERNAL_LLM_MODEL_RESET = "${ApiVersions.V1_PATH_PREFIX}$INTERNAL_LLM_MODEL_RESET"
    const val V1_INTERNAL_LLM_MODEL_PROBE = "${ApiVersions.V1_PATH_PREFIX}$INTERNAL_LLM_MODEL_PROBE"
    const val V1_INTERNAL_AI_KEYWORD_EXPANSIONS = "${ApiVersions.V1_PATH_PREFIX}$INTERNAL_AI_KEYWORD_EXPANSIONS"
    const val V1_INTERNAL_AI_NEWS_SUMMARIES = "${ApiVersions.V1_PATH_PREFIX}$INTERNAL_AI_NEWS_SUMMARIES"
    const val V1_INTERNAL_AI_KEYWORD_QUARANTINES = "${ApiVersions.V1_PATH_PREFIX}$INTERNAL_AI_KEYWORD_QUARANTINES"
    const val V1_INTERNAL_AI_KEYWORD_QUARANTINE_RELEASE =
        "${ApiVersions.V1_PATH_PREFIX}$INTERNAL_AI_KEYWORD_QUARANTINE_RELEASE"
    const val V1_INTERNAL_AI_SUMMARY_WATERMARKS = "${ApiVersions.V1_PATH_PREFIX}$INTERNAL_AI_SUMMARY_WATERMARKS"
    const val V1_INTERNAL_AI_OUTBOXES = "${ApiVersions.V1_PATH_PREFIX}$INTERNAL_AI_OUTBOXES"
    const val V1_INTERNAL_AI_OUTBOX_RECOVER = "${ApiVersions.V1_PATH_PREFIX}$INTERNAL_AI_OUTBOX_RECOVER"
    const val V1_INTERNAL_AI_STORY_SUMMARIES = "${ApiVersions.V1_PATH_PREFIX}$INTERNAL_AI_STORY_SUMMARIES"
    const val V1_INTERNAL_AI_STORY_SUMMARY_RUN = "${ApiVersions.V1_PATH_PREFIX}$INTERNAL_AI_STORY_SUMMARY_RUN"
    const val V1_INTERNAL_AI_STORY_QUARANTINES = "${ApiVersions.V1_PATH_PREFIX}$INTERNAL_AI_STORY_QUARANTINES"
    const val V1_INTERNAL_AI_STORY_QUARANTINE_RELEASE =
        "${ApiVersions.V1_PATH_PREFIX}$INTERNAL_AI_STORY_QUARANTINE_RELEASE"
}
