spring:
  data:
    redis:
      host: localhost
      port: 6379
  mongodb:
    uri: mongodb://localhost:27017/kachi_notification
  kafka:
    bootstrap-servers: localhost:9092

kachi:
  notification:
    worker:
      sender:
        slack:
          webhook-url: ${KACHI_NOTIFICATION_SLACK_WEBHOOK_URL}
        discord:
          webhook-url: ${KACHI_NOTIFICATION_DISCORD_WEBHOOK_URL:}
        telegram:
          bot-token: ${KACHI_NOTIFICATION_TELEGRAM_BOT_TOKEN:}
