spring:
  data:
    redis:
      host: localhost
      port: 6379
  mongodb:
    uri: mongodb://localhost:27017/kachi_notification?replicaSet=rs0
  kafka:
    bootstrap-servers: localhost:9092

kachi:
  notification:
    recipient:
      user-service:
        base-url: ${KACHI_USER_SERVICE_BASE_URL:http://localhost:8080}
