spring:
  application:
    name: user-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

server:
  port: 8080
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health

kachi:
  jwt:
    access-token-ttl: 15m
    refresh-token-ttl: 14d
  user:
    binding:
      link-token-ttl: 10m
