spring:
  mongodb:
    uri: mongodb://localhost:27017/kachi_collector?replicaSet=rs0
    representation:
      uuid: standard
  data:
    mongodb:
      auto-index-creation: true

kachi:
  collector:
    scheduler:
      news:
        enabled: true
    clients:
      user-service:
        base-url: http://localhost:8080
