spring:
  mongodb:
    uri: mongodb://localhost:27017/kachi_collector?replicaSet=rs0
    representation:
      uuid: standard
  data:
    mongodb:
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:9092

kachi:
  collector:
    scheduler:
      news:
        enabled: true
    clients:
      user-service:
        base-url: ${KACHI_USER_SERVICE_BASE_URL:http://localhost:8080}
