spring:
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    uri: mongodb://localhost:27017/kachi_notification_routing?replicaSet=rs0
  kafka:
    bootstrap-servers: localhost:9092

kachi:
  notification:
    routing:
      user-service:
        base-url: http://localhost:8080
